[server]
maxUploadSize = 2048

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 
GOOGLE_API_KEY ="AIzaSyBrz5Y_pG3HdRnXtph1DAkw_HzO4FxF95A"